version: '3' # Certifique-se de especificar a versão correta do Docker Compose

services:
    db:
        image: postgres:latest
        env_file: .env
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data

    desafio_crawler:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: desafio_crawler
        command: /app/start.sh
        volumes:
            - ./desafio_crawler:/app
        stdin_open: true
        tty: true
        ports:
            - 8000:8000

volumes:
    pgdata:
