version: '3' # Certifique-se de especificar a versão correta do Docker Compose

services:
    # db:
    #     image: postgres:12.1
    #     environment:
    #         POSTGRES_USER: postgres
    #         POSTGRES_PASSWORD: postgres

    desafio_crawler:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: desafio_crawler
        command: /app/start.sh
        volumes:
            - ./desafio_crawler:/app
            - /var/run/docker.sock:/var/run/docker.sock
        stdin_open: true
        tty: true
        ports:
            - 8000:8000

volumes:
    pgdata:
