version: '3'

services:
    desafio_crawler:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: desafio_crawler
        command: /app/start.sh
        volumes:
            - ./desafio_crawler:/app
            - /var/run/docker.sock:/var/run/docker.sock
        stdin_open: true
        tty: true
        ports:
            - 8000:8000

volumes:
    pgdata:
